window.__SWE_MANIFEST__=[
 {
  "id": "gen_d32a10d6",
  "tipo": "video",
  "linea": "A_US",
  "escena": "VG2",
  "desc": "La etiqueta luminiscente cobra vida — el plano que cierra el máster de 34s",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1920,
  "h": 1080,
  "dur": 10,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260504_140727_d32a10d6-38bc-4bd3-ae0b-c95fe14d5c20.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_d32a10d6.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_63db8ae3",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "La botella emerge entre lluvia de vino y salpicadura épica sobre fondo negro",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_144417_63db8ae3-09b3-47bf-b5c8-5be6815fb69a.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_63db8ae3.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_8ed2f314",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "Gotas de vino suspendidas revelan la botella Sharp Zombie entre niebla oscura",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_144417_8ed2f314-7c83-4fbd-9306-3fadbc4cf931.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_8ed2f314.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_13f83fce",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "El Rioja se vierte bajo la luna con un resplandor verde sobrenatural",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_144434_13f83fce-ac23-491e-aee8-4b9642bdd12b.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_13f83fce.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_dc32e247",
  "tipo": "video",
  "linea": "A_US",
  "escena": "S7",
  "desc": "Toma del corte vertical para redes — atmósfera de bodega",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_144434_dc32e247-b634-4063-af9e-3bc56ec38332.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_dc32e247.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_0e5ffd25",
  "tipo": "video",
  "linea": "A_US",
  "escena": "GLOW",
  "desc": "La etiqueta Sharp Zombie se enciende en verde neón al apagarse la luz",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 7.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_151234_0e5ffd25-3181-4330-9c72-1b3394e93a22.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_0e5ffd25.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_ce9b6a18",
  "tipo": "video",
  "linea": "A_US",
  "escena": "S8",
  "desc": "Toma del corte vertical para redes — el reveal",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 7.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_151342_ce9b6a18-a02d-49e2-8f4e-6deffe8b6704.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_ce9b6a18.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_f0541995",
  "tipo": "video",
  "linea": "A_US",
  "escena": "GLOW",
  "desc": "La botella Sharp Zombie se enciende con su glow verde en la oscuridad",
  "status": "COMPLETED",
  "primaria": false,
  "w": 720,
  "h": 1280,
  "dur": 6.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260505_151708_f0541995-d5ac-4485-b498-737bbafad47e.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_f0541995.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_b75d0854",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "La botella Sharp Zombie emerge entre salpicaduras de vino sobre fondo negro",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260506_173948_b75d0854-fb24-4d3e-b307-aaa8b37b23be.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_b75d0854.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_df595194",
  "tipo": "video",
  "linea": "A_US",
  "escena": "S6",
  "desc": "Toma del corte vertical para redes — los viñedos de noche",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 5.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260506_173948_df595194-ad78-4a9e-9b24-58f6feec26e9.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_df595194.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_10bb1f81",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "Reveal elegante de Sharp Zombie Rioja y White sobre mármol con bokeh cálido",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 6.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260506_173952_10bb1f81-756f-431f-b6da-6389deca1424.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_10bb1f81.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_a86ff6cd",
  "tipo": "video",
  "linea": "A_US",
  "escena": "S9",
  "desc": "Toma del corte vertical para redes — plano de cierre",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 6.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260506_173952_a86ff6cd-7bf0-4bb7-9053-d9954b79ae60.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_a86ff6cd.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_6dbea238",
  "tipo": "video",
  "linea": "B_JAPON",
  "escena": "ESC3",
  "desc": "INTRIGUE — los espíritus del vino se materializan en el jardín zen",
  "status": "COMPLETED",
  "primaria": true,
  "w": 1280,
  "h": 720,
  "dur": 8.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260508_151802_6dbea238-bbff-4a10-843b-a0bf0b611dd2.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_6dbea238.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_80bdaa99",
  "tipo": "video",
  "linea": "B_JAPON",
  "escena": "ESC4",
  "desc": "REVEAL — el producto hero brilla entre luz suave japonesa",
  "status": "COMPLETED",
  "primaria": true,
  "w": 1280,
  "h": 720,
  "dur": 8.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260508_151847_80bdaa99-9462-4f09-a716-48a9bb648885.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_80bdaa99.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_be95dc65",
  "tipo": "video",
  "linea": "B_JAPON",
  "escena": "ESC6",
  "desc": "CLOSE — el brindis final con cierre japonés",
  "status": "COMPLETED",
  "primaria": true,
  "w": 1280,
  "h": 716,
  "dur": 5,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260508_152149_be95dc65-fac7-45a5-b02e-c538b4d8e4db.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_be95dc65.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_cb973c3c",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "Copa de Rioja en penumbra teal y uvas maduras en macro cinematográfico",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260509_233804_cb973c3c-59f0-4a40-8d9b-0b4bd9d6f85a.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_cb973c3c.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_578b849e",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "Elegante zombie sirve Sharp Zombie entre niebla y neón rojo de bodega",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260509_234914_578b849e-1237-4ab4-933c-ab6b62a6d1f7.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_578b849e.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_fc489abb",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC5",
  "desc": "Un zombie esquelético emerge de la tierra alzando la botella Sharp Zombie",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 8.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260514_185824_fc489abb-da7a-4158-8503-a6f1b64b05ce.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_fc489abb.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_a6807288",
  "tipo": "video",
  "linea": "A_US",
  "escena": "ESC2",
  "desc": "Sepulturero y farol junto a una tumba abierta bajo la niebla nocturna",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1080,
  "h": 1920,
  "dur": 4.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260515_105023_a6807288-898f-4d10-a54e-ac38f65ddc47.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_a6807288.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_666a239e",
  "tipo": "video",
  "linea": "C_SPIDERVERSE",
  "escena": "S2",
  "desc": "Leo y Mia descubren la botella derramada en pleno estilo cómic Spider-Verse",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1920,
  "h": 1080,
  "dur": 5,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260707_220945_666a239e-eb8d-476a-abd5-45dd39a6f4c0.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_666a239e.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_dbe82921",
  "tipo": "video",
  "linea": "C_SPIDERVERSE",
  "escena": "S7",
  "desc": "MIA escapa de los vine-spirits con la botella entre onomatopeyas de cómic",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 720,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260711_115723_dbe82921-57df-4660-85d1-e5e1dce1b89a.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_dbe82921.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_c7c9ec9a",
  "tipo": "video",
  "linea": "C_SPIDERVERSE",
  "escena": "S12",
  "desc": "Mia presenta la botella Sharp Zombie entre onomatopeyas y tramas de cómic",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 720,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260711_115725_c7c9ec9a-edfd-4703-9dc7-bcf05b32f8d7.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_c7c9ec9a.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_33c6c4ca",
  "tipo": "video",
  "linea": "C_SPIDERVERSE",
  "escena": "S2",
  "desc": "Mia presume la botella Sharp Zombie antes de un tropiezo de cómic explosivo",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 720,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260711_115726_33c6c4ca-dbb6-457a-a7e4-6a67b6b4347a.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_33c6c4ca.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_c460a874",
  "tipo": "video",
  "linea": "C_SPIDERVERSE",
  "escena": "S12",
  "desc": "Mia estilo cómic bebe Sharp Zombie con ojos en X sobre fondo neutro",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 720,
  "dur": 15.1,
  "src": "https://d8j0ntlcm91z4.cloudfront.net/user_3BP9AlN7MxU50eaw9ZlO6ny5hI2/hf_20260711_115729_c460a874-6474-4ecd-9278-b5dc74ceab26.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/gen_c460a874.webp",
  "origen": "higgsfield"
 },
 {
  "id": "gen_e35ad418",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "SHEET",
  "desc": "Hojas de modelo de Leo y Mia con poses y expresiones estilo cómic",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_e35ad418.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_da4be7e5",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "SHEET",
  "desc": "Hoja de modelo cómic: troupe de vine-spirits, líder y shiba inu",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_da4be7e5.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_b3e47816",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S1",
  "desc": "Leo y Mia brindan bajo la luna en picnic estilo cómic Spider-Verse",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_b3e47816.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_fa3d8ef3",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S1",
  "desc": "Leo y Mia de picnic nocturno bajo la luna, botella Sharp Zombie protagonista",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_fa3d8ef3.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_b4ba6ae6",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S2",
  "desc": "Leo y Mia descubren la botella Sharp Zombie derramándose en el viñedo nocturno",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_b4ba6ae6.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_23e93690",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S3",
  "desc": "Los vine-spirits irrumpen entre tramas de cómic ante la pareja atónita",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_23e93690.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_51867710",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S6",
  "desc": "Leo y Mia huyen del viñedo con la botella entre vine-spirits y shiba",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_51867710.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_5df0a660",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S12",
  "desc": "Reveal de botellas Sharp Zombie en bodega con tramas de cómic vibrantes",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_5df0a660.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_10b65814",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S3",
  "desc": "Los vine-spirits emergen del viñedo entre onomatopeyas y tramas de cómic",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_10b65814.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_49944483",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S7",
  "desc": "Leo y Mia huyen de los vine-spirits con la botella brillando en glow verde",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_49944483.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_01dcd1d8",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S12",
  "desc": "Los vine-spirits bailan en la bodega y revelan la botella Sharp Zombie",
  "status": "COMPLETED",
  "primaria": false,
  "w": 5504,
  "h": 3072,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_01dcd1d8.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_b3b39fa4",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "S12",
  "desc": "Mia presenta la botella Sharp Zombie entre onomatopeyas pop y tramas de cómic",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1376,
  "h": 768,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_b3b39fa4.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "gen_64fdc589",
  "tipo": "imagen",
  "linea": "C_SPIDERVERSE",
  "escena": "OTRO",
  "desc": "Página de cómic pop: zombies y Sharp Zombie a todo color",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1024,
  "h": 1024,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/gen_64fdc589.webp",
  "poster": null,
  "origen": "higgsfield"
 },
 {
  "id": "master_34s",
  "linea": "A_US",
  "escena": "MASTER",
  "desc": "Máster hero 34s con escena glow final — versión definitiva v2",
  "w": 960,
  "h": 540,
  "dur": 34,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/master_34s.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/master_34s.webp",
  "origen": "montaje"
 },
 {
  "id": "master_28s",
  "linea": "A_US",
  "escena": "MASTER",
  "desc": "Máster hero 28s — primera versión, sin escena glow",
  "w": 960,
  "h": 540,
  "dur": 28,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/master_28s.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/master_28s.webp",
  "origen": "montaje"
 },
 {
  "id": "vertical_9x16",
  "linea": "A_US",
  "escena": "MASTER_V",
  "desc": "Montaje vertical 9:16 para TikTok, Reels y Shorts",
  "w": 540,
  "h": 960,
  "dur": 31,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/vertical_9x16.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/vertical_9x16.webp",
  "origen": "montaje"
 },
 {
  "id": "maria_ad_v1",
  "linea": "EXTRA",
  "escena": "MARIA",
  "desc": "Ad corporativo SWE — versión sandbox con marca de agua",
  "w": 960,
  "h": 540,
  "dur": 38,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/maria_ad_v1.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/maria_ad_v1.webp",
  "origen": "montaje"
 },
 {
  "id": "sv_c2_derrame",
  "linea": "C_SPIDERVERSE",
  "escena": "S3",
  "desc": "Clip piloto animado: el derrame de la botella",
  "w": 960,
  "h": 540,
  "dur": 10,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/sv_c2_derrame.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/sv_c2_derrame.webp",
  "origen": "montaje"
 },
 {
  "id": "sv_c5_baile",
  "linea": "C_SPIDERVERSE",
  "escena": "S11",
  "desc": "Clip piloto animado: el baile de los vine-spirits",
  "w": 960,
  "h": 540,
  "dur": 15,
  "tipo": "video",
  "status": "COMPLETED",
  "primaria": true,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/video/sv_c5_baile.mp4",
  "poster": "https://mohamedmadrazo.github.io/swe-sz-media/poster/sv_c5_baile.webp",
  "origen": "montaje"
 },
 {
  "id": "zdir_a_classic",
  "linea": "C_SPIDERVERSE",
  "escena": "ZDIR",
  "desc": "Dirección A — CLASSIC: zombie de cómic tradicional",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/zdir_a_classic.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "zdir_b_vine",
  "linea": "C_SPIDERVERSE",
  "escena": "ZDIR",
  "desc": "Dirección B — VINE: espíritu de la viña, sarmientos y uvas",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/zdir_b_vine.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "zdir_c_cool",
  "linea": "C_SPIDERVERSE",
  "escena": "ZDIR",
  "desc": "Dirección C — COOL: zombie con actitud, gafas y estilo urbano",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/zdir_c_cool.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "zdir_d_yokai",
  "linea": "C_SPIDERVERSE",
  "escena": "ZDIR",
  "desc": "Dirección D — YŌKAI: espíritu folclórico japonés",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/zdir_d_yokai.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b1_picnic",
  "linea": "C_SPIDERVERSE",
  "escena": "B1",
  "desc": "Board 1 — El picnic bajo la luna",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b1_picnic.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b2_derrame",
  "linea": "C_SPIDERVERSE",
  "escena": "B2",
  "desc": "Board 2 — El derrame de la botella",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b2_derrame.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b3_emergen",
  "linea": "C_SPIDERVERSE",
  "escena": "B3",
  "desc": "Board 3 — Los vine-spirits emergen",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b3_emergen.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b4_persecucion",
  "linea": "C_SPIDERVERSE",
  "escena": "B4",
  "desc": "Board 4 — La persecución por el viñedo",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b4_persecucion.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b5_baile",
  "linea": "C_SPIDERVERSE",
  "escena": "B5",
  "desc": "Board 5 — El baile",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b5_baile.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_board_b6_reveal",
  "linea": "C_SPIDERVERSE",
  "escena": "B6",
  "desc": "Board 6 — El reveal final",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_board_b6_reveal.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_sheet_pareja",
  "linea": "C_SPIDERVERSE",
  "escena": "SHEET",
  "desc": "Character sheet — Leo y Mia",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_sheet_pareja.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "sv_sheet_troupe",
  "linea": "C_SPIDERVERSE",
  "escena": "SHEET",
  "desc": "Character sheet — Troupe de vine-spirits y shiba",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/sv_sheet_troupe.webp",
  "poster": null,
  "origen": "local"
 },
 {
  "id": "producto_real",
  "linea": "EXTRA",
  "escena": "PRODUCT",
  "desc": "El producto real: botellas con etiqueta glow",
  "tipo": "imagen",
  "status": "COMPLETED",
  "primaria": false,
  "w": 1280,
  "h": 0,
  "dur": 0,
  "src": "https://mohamedmadrazo.github.io/swe-sz-media/img/producto_real.webp",
  "poster": null,
  "origen": "local"
 }
];